services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: stride
      POSTGRES_PASSWORD: stride
      POSTGRES_DB: stride
    ports:
      - "5433:5432"           # host 5433 → container 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  db_data:
